name: Deploy to Render

on:
  push:
    branches:
      - master  # ou a branch que deseja usar para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Disparar Deploy na Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}